name: Testing on push

on: push

env:
    DBUSER: secrets.DBUSER
    DBPASSWD: secrets.DBPASSWD
    TESTDBNAME: secrets.TESTDBNAME
jobs:
    test:
        name: Test passes
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Install modules
              run: npm ci

            - name: Testing
              run: npm run test
